services:
  python-server:
    build: .
    volumes:
      - ./target-folder:/mnt/target-folder  # Watching and processing files initially in target-folder
      - ./storage:/storage  # Processed files will be stored in the storage directory
      - ./dummy-folder:/mnt/dummy-folder  # Added volume for dummy files during scanning
    depends_on:
      - escan
      - mcafee
      - comodo
      - windows-defender
      - fprot
    networks:
      - scan_network
    environment:
      - WATCH_FOLDER=/mnt/target-folder
      - STORAGE_FOLDER=/storage
      - DUMMY_FOLDER=/mnt/dummy-folder

  escan:
    image: malice/escan:updated
    command: web
    ports:
      - '3994:3993'
    networks:
      - scan_network

  mcafee:
    image: malice/mcafee:updated
    command: web
    ports:
      - '3993:3994'
    networks:
      - scan_network

  comodo:
    image: malice/comodo:updated
    command: web
    ports:
      - '3995:3993'
    networks:
      - scan_network

  windows-defender:
    image: malice/windows-defender
    command: web
    ports:
      - '3996:3993'
    networks:
      - scan_network

  fprot:
    image: malice/fprot:updated
    command: web
    ports:
      - '3997:3993'
    networks:
      - scan_network

networks:
  scan_network:
    driver: bridge
