version: '3.8'
services:
  python-server:
    build:
      context: .
    volumes:
      - "C:/Users/SARTHAK/Desktop/sih-2024/python-server:/app"  # Ensure the entire folder is mapped to /app
    ports:
      - "5000:5000"
    command: python /app/main.py  # Ensure that main.py is run when the container starts

  management-server:
    build:
      context: .
    volumes:
      - "C:/Users/SARTHAK/Desktop/sih-2024/python-server/target_folder:/app/target_folder"  # Specify the destination folder inside the container
      - "C:/Users/SARTHAK/Desktop/sih-2024/python-server/file_storage:/app/file_storage"
    ports:
      - "5001:5001"
