version: '3.8'

services:
  watcher:
    build:
      context: .
    volumes:
      - ./target-folder:/mnt/target-folder
      - ./storage:/storage
    depends_on:
      - clamav

  clamav:
    image: clamav/clamav
    volumes:
      - ./storage:/shared
    ports:
      - "3310:3310"  # ClamAV daemon port
